name: TheNextShot
favicon: null
layout_spectrum: 0.4771194157656282
typography_spectrum: 0.4775832574814558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7107986293267459
  lightness: 0.5833524344488978
  saturation: 0.8789626653306186
  rhythmicContrast: 0.6655184137634933
purpose: []
